spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: machine_factory
  flyway:
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    #open-in-view: false (to solve the warning)
