spring.profiles.active: h2

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: machine_factory
  data:
    web:
      pageable:
        default-page-size: 1 #predefined page size for get requests
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
